import { Data } from ".";

export default [
    {
      id: 1,
      first_name: "Alfonso",
      last_name: "Crawford",
      email_address: "vitae@ad.co.uk",
    },
    {
      id: 2,
      first_name: "Kyle",
      last_name: "Mercado",
      email_address: "tellus@etlibero.ca",
    },
    {
      id: 3,
      first_name: "Aubrey",
      last_name: "Warner",
      email_address: "auctor.nunc.nulla@Utsemperpretium.net",
    },
    {
      id: 4,
      first_name: "Yeo",
      last_name: "Mercado",
      email_address: "pede.sagittis@Curabitur.co.uk",
    },
    {
      id: 5,
      first_name: "Dominic",
      last_name: "Ortiz",
      email_address: "ornare@pretium.edu",
    },
    {
      id: 6,
      first_name: "Chaney",
      last_name: "French",
      email_address: "Sed.diam.lorem@SuspendissesagittisNullam.ca",
    },
    {
      id: 7,
      first_name: "Gwendolyn",
      last_name: "Thompson",
      email_address: "felis.Nulla@Curabiturconsequat.net",
    },
    {
      id: 8,
      first_name: "Deborah",
      last_name: "Holden",
      email_address: "amet@dictum.com",
    },
    {
      id: 9,
      first_name: "Barrett",
      last_name: "Ballard",
      email_address: "accumsan.sed@Sed.ca",
    },
    {
      id: 10,
      first_name: "Kathleen",
      last_name: "Gilbert",
      email_address: "congue@Nullaeuneque.ca",
    },
    {
      id: 11,
      first_name: "Ferris",
      last_name: "Mcguire",
      email_address: "Nam.nulla@magnaetipsum.com",
    },
    {
      id: 12,
      first_name: "Cassady",
      last_name: "Navarro",
      email_address: "est@Integer.net",
    },
    {
      id: 13,
      first_name: "Gregory",
      last_name: "Hinton",
      email_address: "Lorem.ipsum@idmagnaet.net",
    },
    {
      id: 14,
      first_name: "Timon",
      last_name: "MerHebertcado",
      email_address: "luctus.sit.amet@non.com",
    },
    {
      id: 15,
      first_name: "Aphrodite",
      last_name: "Drake",
      email_address: "nisl@interdumNuncsollicitudin.ca",
    },
    {
      id: 16,
      first_name: "Hammett",
      last_name: "Robertson",
      email_address: "Vivamus@lectusasollicitudin.net",
    },
    {
      id: 17,
      first_name: "Erich",
      last_name: "Pratt",
      email_address: "enim@scelerisquemollis.ca",
    },
    {
      id: 18,
      first_name: "Walker",
      last_name: "Ware",
      email_address: "facilisis@risusDonecegestas.edu",
    },
    {
      id: 19,
      first_name: "Kelly",
      last_name: "Kim",
      email_address: "Nulla.interdum.Curabitur@adipiscing.net",
    },
    {
      id: 20,
      first_name: "Kyle",
      last_name: "Mercado",
      email_address: "tellus@etlibero.ca",
    },
    {
      id: 21,
      first_name: "Clark",
      last_name: "Bradshaw",
      email_address: "semper@mi.net",
    },
    {
      id: 22,
      first_name: "Dacey",
      last_name: "Merrill",
      email_address: "non@mauris.co.uk",
    },
    {
      id: 23,
      first_name: "Vanna",
      last_name: "Blackwell",
      email_address: "laoreet.lectus@maurisaliquameu.edu",
    },
    {
      id: 24,
      first_name: "Hammett",
      last_name: "Robertson",
      email_address: "Vivamus@lectusasollicitudin.net",
    },
    {
      id: 25,
      first_name: "Erich",
      last_name: "Pratt",
      email_address: "enim@scelerisquemollis.ca",
    },
    {
      id: 26,
      first_name: "Dacey",
      last_name: "Merrill",
      email_address: "non@mauris.co.uk",
    },
    {
      id: 27,
      first_name: "Vanna",
      last_name: "Blackwell",
      email_address: "laoreet.lectus@maurisaliquameu.edu",
    },
    {
      id: 28,
      first_name: "Jeanette",
      last_name: "Logan",
      email_address: "sed.dolor.Fusce@Aeneanegestas.com",
    },
    {
      id: 29,
      first_name: "Lee",
      last_name: "Cotton",
      email_address: "pharetra@metusInlorem.edu",
    },
    {
      id: 30,
      first_name: "Harry",
      last_name: "Potter",
      email_address: "harrypotter@etlibero.ca",
    },
    {
      id: 31,
      first_name: "Hermione",
      last_name: "granger",
      email_address: "granger@etlibero.ca",
    },
    {
      id: 32,
      first_name: "Ron",
      last_name: "Weasley",
      email_address: "Weasley@etlibero.ca",
    },
    {
      id: 33,
      first_name: "Remus",
      last_name: "Lupin",
      email_address: "Lupin@etlibero.ca",
    },
    {
      id: 34,
      first_name: "Luna",
      last_name: "Lovegood",
      email_address: "Lovegood@etlibero.ca",
    },
    {
      id: 35,
      first_name: "Ginny",
      last_name: "Weasley",
      email_address: "Ginny@etlibero.ca",
    },
    {
      id: 36,
      first_name: "Cho",
      last_name: "Chang",
      email_address: "Chang@etlibero.ca",
    },
    {
      id: 37,
      first_name: "Minerva",
      last_name: "McGonagall",
      email_address: "Minerva@etlibero.ca",
    },
    {
      id: 38,
      first_name: "James",
      last_name: "Potter",
      email_address: "james@etlibero.ca",
    },
    {
      id: 39,
      first_name: "Lily",
      last_name: "Potter",
      email_address: "lily@etlibero.ca",
    },
    {
      id: 40,
      first_name: "Albus",
      last_name: "Dumbledore",
      email_address: "Dumbledore@etlibero.ca",
    },
] as Data[];
  